"""Tool namespace for tars-vault MCP server.

Each tool module exposes a single callable named identically to the module.
"""
from . import (
    append_note,
    archive_note,
    classify_file,
    create_note,
    detect_near_duplicates,
    format_wikilink,
    fts_search,
    move_note,
    read_note,
    read_system_file,
    refresh_integrations,
    rerank,
    resolve_alias,
    resolve_capability,
    runtime_info,
    scan_secrets,
    scaffold_workspace,
    search_by_tag,
    semantic_search,
    update_frontmatter,
    write_note_from_content,
)

__all__ = [
    "append_note",
    "archive_note",
    "classify_file",
    "create_note",
    "detect_near_duplicates",
    "format_wikilink",
    "fts_search",
    "move_note",
    "read_note",
    "read_system_file",
    "refresh_integrations",
    "rerank",
    "resolve_alias",
    "resolve_capability",
    "runtime_info",
    "scan_secrets",
    "scaffold_workspace",
    "search_by_tag",
    "semantic_search",
    "update_frontmatter",
    "write_note_from_content",
]
